# Generated by Django 4.2.4 on 2024-05-28 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageupload',
            name='title',
        ),
    ]
